version: '3.9'
services: 
  frontend:
    build: frontend
    ports: 
      - '3000:3000'
  image: 
    build: image
    ports: 
      - '4001:4001'
  event-bus: 
    build: event-bus
  wall_storage: 
    build: wall_storage
    ports: 
      - '4000:4000'
  query: 
    build: query
    ports: 
      - '4002:4002'
  votes: 
    build: votes
    ports: 
      - '4003:4003'
